version: '3'
services: 
    web_test: #Load Balancer
        image: nginx:latest
        container_name: NGINX
        ports: 
            - 80:80
        volumes:
            - <local drive>\NGINX:/etc/nginx/conf.d
            
        depends_on: 
            - luis1
            - luis2

    luis1: #LUIS Instance 1
        image: mcr.microsoft.com/azure-cognitive-services/language/luis
        container_name: LUIS1
        ports: 
            - 5000:5000
        volumes: 
            - <local drive>\input:/input
            - <local drive>\output:/output
        environment:
            - Eula=accept
            - Billing=<endpoint url> 
            - ApiKey=<ApiKey>

    luis2: #LUIS Instance 2
        image: mcr.microsoft.com/azure-cognitive-services/language/luis
        container_name: LUIS2
        ports: 
            - 5001:5000
        volumes: 
            - <local drive>\input:/input
            - <local drive>\output:/output
        environment:
            - Eula=accept
            - Billing=<endpoint url>
            - ApiKey=<ApiKey>

    TextAnalytics: # Text Analytics
        image: mcr.microsoft.com/azure-cognitive-services/textanalytics/sentiment
        container_name: TextAnalytics
        ports: 
            - 5002:5000
        environment:
            - Eula=accept 
            - Billing=<endpoint url>
            - ApiKey=<ApiKey>

    liteSQL: # SQL Instance
        image: mcr.microsoft.com/azure-sql-edge
        container_name: LightSQL
        ports: 
            - 1433:1433
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Aa123456789
            - MSSQL_PID=Developer
        volumes: 
            - <local drive>\DB\Data:/var/opt/mssql/data
            - <local drive>\DB\log:/var/opt/mssql/log