version: '3'
services: 
    web_test: #Load Balancer
        image: nginx:latest
        container_name: NGINX
        ports: 
            - 80:80
        volumes:
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\NGINX:/etc/nginx/conf.d
            
        depends_on: 
            - luis1
            - luis2

    luis1: #LUIS Instance 1
        image: mcr.microsoft.com/azure-cognitive-services/language/luis
        container_name: LUIS1
        ports: 
            - 5000:5000
        volumes: 
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\Luis\input:/input
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\Luis\output:/output
        environment:
            - Eula=accept
            - Billing=https://westeurope.api.cognitive.microsoft.com 
            - ApiKey=1002428e39cf48118f6d378ee1499bb7

    luis2: #LUIS Instance 2
        image: mcr.microsoft.com/azure-cognitive-services/language/luis
        container_name: LUIS2
        ports: 
            - 5001:5000
        volumes: 
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\Luis\input:/input
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\Luis\output:/output
        environment:
            - Eula=accept
            - Billing=https://westeurope.api.cognitive.microsoft.com 
            - ApiKey=1002428e39cf48118f6d378ee1499bb7

    TextAnalytics: # Text Analytics
        image: mcr.microsoft.com/azure-cognitive-services/textanalytics/sentiment
        container_name: TextAnalytics
        ports: 
            - 5002:5000
        environment:
            - Eula=accept 
            - Billing=https://testanalytics.cognitiveservices.azure.com/
            - ApiKey=a8b87a724e26498fa6435f4593cf5c07

    liteSQL: # SQL Instance
        image: mcr.microsoft.com/azure-sql-edge
        container_name: LightSQL
        ports: 
            - 1433:1433
        environment: 
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Aa123456789
            - MSSQL_PID=Developer
        volumes: 
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\DB\Data:/var/opt/mssql/data
            - C:\Users\arlio\OneDrive\Desktop\Cognitive\Containers\DB\log:/var/opt/mssql/log